/**
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-types.mjs
 */

export type TableName = 'businesses' | 'branches' | 'app_users' | 'customers' | 'staff' | 'rooms' | 'membership_plans' | 'customer_memberships' | 'appointments' | 'payments' | 'debts' | 'expenses' | 'inventory' | 'audit_logs' | 'notification_logs' | 'commission_rules' | 'calendar_blocks' | 'services' | 'customer_media' | 'z_reports' | 'user_branch_access' | 'booking_settings' | 'packages' | 'package_definitions' | 'payment_definitions' | 'bank_accounts' | 'expense_categories' | 'referral_sources' | 'consent_form_templates' | 'ai_insights';

export interface Business {
    id: string;
    name: string;
    ownerName: any;
    plan: string;
    expiryDate: any;
    status: string;
    mrr: number;
    maxUsers: number;
    createdAt?: string;
    slug: string;
    maxBranches: number;
}

export interface Branch {
    id: string;
    businessId?: string;
    name: string;
    location: any;
    createdAt?: string;
    address: any;
    phone: any;
    status: string;
}

export interface AppUser {
    id: string;
    businessId?: string;
    branchId?: string;
    role: string;
    name: string;
    email: string;
    permissions: string[];
    createdAt?: string;
    allowedBranches: string[];
}

export interface Customer {
    id: string;
    businessId?: string;
    name: string;
    phone: any;
    email: any;
    birthdate: any;
    segment: string;
    note?: any;
    isChurnRisk: boolean;
    createdAt?: string;
    country: string;
    language: string;
    referenceCode: any;
    tags: string[];
    address: any;
}

export interface Staff {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    role: any;
    status: string;
    weeklyOffDay: number;
    createdAt?: string;
    staffType: string;
    isVisibleOnCalendar: boolean;
    sortOrder: number;
    canLoginSystem: boolean;
    canLoginMobile: boolean;
    staffGroup: string;
    lastLoginAt: any;
}

export interface Room {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    status: string;
    createdAt?: string;
    category?: string;
    color?: string;
}

export interface MembershipPlan {
    id: string;
    businessId?: string;
    name: string;
    price: number;
    periodDays: number;
    benefits: string[];
    allowedServices: string[];
    sessionsPerMonth: number;
    createdAt?: string;
}

export interface CustomerMembership {
    id: string;
    businessId?: string;
    customerId?: string;
    planId?: string;
    startDate: string;
    expiryDate: any;
    remainingSessions: number;
    status: string;
    createdAt?: string;
}

export interface Appointment {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    customerName: string;
    service: string;
    staffName: string;
    staffId?: string;
    date: string;
    time: string;
    duration: number;
    status: string;
    price: number;
    depositPaid: number;
    isOnline: boolean;
    packageId?: any;
    membershipId?: any;
    syncStatus?: string;
    createdAt?: string;
    updatedAt?: string;
    roomId?: string;
    selectedRegions: string[];
    isPaid: boolean;
    paymentId?: string;
    isPackageUsage: boolean;
    bookingNotes: string;
}

export interface Payment {
    id: string;
    businessId?: string;
    branchId?: string;
    appointmentId?: any;
    customerId?: string;
    customerName: string;
    service: any;
    methods: any;
    totalAmount: number;
    date: string;
    note?: any;
    syncStatus?: string;
    createdAt?: string;
    paymentDefinitionId?: string;
}

export interface Debt {
    id: string;
    businessId?: string;
    customerId?: string;
    appointmentId?: string;
    amount: number;
    dueDate: any;
    description: any;
    status: string;
    createdAt?: string;
    branchId?: string;
}

export interface Expense {
    id: string;
    businessId?: string;
    desc: string;
    amount: number;
    category: string;
    date: string;
    user: any;
    createdAt?: string;
    branchId?: string;
}

export interface Product {
    id: string;
    businessId?: string;
    name: string;
    category: string;
    price: number;
    stock: number;
    createdAt?: string;
}

export interface AuditLog {
    id: string;
    businessId?: string;
    date: string;
    customerName: any;
    action: string;
    oldValue: any;
    newValue: any;
    user: any;
    createdAt?: string;
}

export interface NotificationLog {
    id: string;
    businessId?: string;
    customerId?: string;
    type: string;
    content: string;
    status: string;
    sentAt: string;
}

export interface CommissionRule {
    id: string;
    businessId?: string;
    staffId?: string;
    serviceName: any;
    type: string;
    value: number;
    createdAt?: string;
}

export interface CalendarBlock {
    id: string;
    businessId?: string;
    branchId?: string;
    staffId?: string;
    date: string;
    time: string;
    duration: number;
    reason: string;
    createdAt?: string;
}

export interface Service {
    id: string;
    businessId?: string;
    name: string;
    duration: number;
    price: number;
    color: string;
    createdAt?: string;
    isPublic: boolean;
    imageUrl: any;
    category: string;
    consumables: any;
}

export interface CustomerMedia {
    id: string;
    businessId?: string;
    customerId?: string;
    fileUrl: string;
    fileType: string;
    note?: string;
    createdAt?: string;
}

export interface ZReport {
    id: string;
    businessId?: string;
    branchId?: string;
    reportDate: string;
    expectedNakit: number;
    actualNakit: number;
    expectedKart: number;
    actualKart: number;
    expectedHavale: number;
    actualHavale: number;
    totalDifference: number;
    closedBy: any;
    notes: any;
    createdAt?: string;
}

export interface UserBranchAccess {
    userId?: string;
    businessId?: string;
    branchId?: string;
}

export interface BookingSettings {
    id: string;
    businessId?: string;
    isEnabled: boolean;
    requireDeposit: boolean;
    depositPercentage: number;
    allowStaffSelect: boolean;
    bookingMessage: any;
    accentColor: string;
    createdAt?: string;
    updatedAt?: string;
}

export interface Package {
    id: string;
    businessId?: string;
    customerId?: string;
    name: string;
    serviceName: any;
    totalSessions: number;
    usedSessions: number;
    price: number;
    expiry: any;
    createdAt?: string;
    updatedAt?: string;
    definitionId?: string;
}

export interface PackageDefinition {
    id: string;
    businessId?: string;
    name: string;
    groupName: any;
    details: any;
    price: number;
    totalSessions: number;
    isActive: boolean;
    createdAt?: string;
}

export interface PaymentDefinition {
    id: string;
    businessId?: string;
    name: string;
    type: string;
    isActive: boolean;
    createdAt?: string;
    updatedAt?: string;
}

export interface BankAccount {
    id: string;
    businessId?: string;
    bankName: string;
    branchName: any;
    accountNo: any;
    iban: any;
    currency: string;
    isActive: boolean;
    createdAt?: string;
}

export interface ExpenseCategory {
    id: string;
    businessId?: string;
    name: string;
    description: any;
    createdAt?: string;
}

export interface ReferralSource {
    id: string;
    businessId?: string;
    name: string;
    createdAt?: string;
}

export interface ConsentFormTemplate {
    id: string;
    businessId?: string;
    name: string;
    content: any;
    createdAt?: string;
    updatedAt?: string;
}

export interface AiInsight {
    id: string;
    businessId?: string;
    title: string;
    desc: string;
    impact: string;
    category: string;
    suggestedAction: any;
    createdAt?: string;
}

