/**
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-types.mjs
 */

export type TableName = 'notification_logs' | 'marketing_rules' | 'dynamic_pricing_rules' | 'customer_wallets' | 'wallet_transactions' | 'consultation_body_maps' | 'inventory_usage_norms' | 'loyalty_settings' | 'webhooks' | 'pricing_rules' | 'inventory_categories' | 'temp_migrations' | 'z_reports' | 'inventory_transfers' | 'package_usage_history' | 'customer_insights' | 'customer_biometrics' | 'technogym_sync_logs' | 'coupons' | 'notifications' | 'whatsapp_queue' | 'ai_token_logs' | 'system_config' | 'pending_agent_actions' | 'saas_plans' | 'saas_invoices' | 'webhook_events' | 'payment_links' | 'businesses' | 'branches' | 'app_users' | 'user_branch_access' | 'staff' | 'services' | 'inventory' | 'rooms' | 'customers' | 'customer_media' | 'membership_plans' | 'referral_sources' | 'customer_memberships' | 'package_definitions' | 'packages' | 'payment_definitions' | 'payments' | 'appointments' | 'calendar_blocks' | 'debts' | 'quotes' | 'consent_form_templates' | 'bank_accounts' | 'expenses' | 'expense_categories' | 'audit_logs' | 'ai_insights' | 'commission_rules' | 'booking_settings' | 'system_announcements' | 'tenant_modules';

export interface NotificationLog {
    id: string;
    businessId?: string;
    customerId?: string;
    type: string;
    content: string;
    status: string;
    sentAt: string;
    triggerSource: string;
}

export interface MarketingRule {
    id: string;
    businessId?: string;
    name: string;
    triggerType: string;
    threshold: any;
    messageTemplate: string;
    isActive: boolean;
    createdAt?: string;
    updatedAt?: string;
}

export interface DynamicPricingRule {
    id: string;
    businessId?: string;
    name: string;
    dayOfWeek: any;
    modifierPercent: number;
    isActive: boolean;
    createdAt?: string;
}

export interface CustomerWallet {
    id: string;
    businessId?: string;
    customerId?: string;
    balance: number;
    loyaltyPoints: number;
    updatedAt?: string;
}

export interface WalletTransaction {
    id: string;
    businessId?: string;
    walletId?: string;
    type: string;
    amount: number;
    points: number;
    description: any;
    createdAt?: string;
}

export interface ConsultationBodyMap {
    id: string;
    businessId?: string;
    appointmentId?: string;
    customerId?: string;
    mapData: any;
    isCritical: boolean;
    createdAt?: string;
}

export interface InventoryUsageNorm {
    id: string;
    businessId?: string;
    serviceId?: string;
    productId?: string;
    amountPerService: number;
    createdAt?: string;
}

export interface LoyaltySetting {
    id: string;
    businessId?: string;
    isEnabled: boolean;
    pointsPerCurrency: number;
    minPointsToSpend: number;
    updatedAt?: any;
}

export interface Webhook {
    id: string;
    businessId?: string;
    name: string;
    url: string;
    events: string[];
    isActive: boolean;
    createdAt?: any;
}

export interface PricingRule {
    id: string;
    businessId?: string;
    name: string;
    modifierPercent: number;
    isActive: boolean;
    createdAt?: any;
}

export interface InventoryCategorie {
    id: string;
    businessId?: string;
    name: string;
    color: any;
    createdAt?: string;
}

export interface TempMigration {
    id: string;
    businessId?: string;
    branchId?: string;
    dataType: string;
    rawData: any;
    status: string;
    systemNote: any;
    createdAt?: string;
    updatedAt?: string;
}

export interface ZReport {
    id: string;
    businessId?: string;
    branchId?: string;
    reportDate: string;
    expectedNakit: number;
    actualNakit: number;
    expectedKart: number;
    actualKart: number;
    totalDifference: number;
    aiSummary: any;
    notes: any;
    closedBy: any;
    createdAt?: string;
    closureNotes: string;
    closedByUserId?: string;
    expectedHavale: number;
    actualHavale: number;
}

export interface InventoryTransfer {
    id: string;
    businessId?: string;
    fromBranchId?: string;
    toBranchId?: string;
    productId?: string;
    quantity: number;
    pricePerUnit: number;
    transferType: string;
    createdAt?: string;
    createdBy: string;
}

export interface PackageUsageHistory {
    id: string;
    businessId?: string;
    packageId?: string;
    customerId?: string;
    action: string;
    sessionsImpact: number;
    appointmentId?: string;
    note?: any;
    createdAt?: any;
}

export interface CustomerInsight {
    id: string;
    businessId?: string;
    customerId?: string;
    insightType: string;
    content: any;
    recommendation: any;
    createdAt?: string;
}

export interface CustomerBiometric {
    id: string;
    businessId?: string;
    customerId?: string;
    weight: number;
    bodyFatPercent: number;
    muscleFatPercent: number;
    visceralFatLevel: any;
    basalMetabolism: any;
    wellnessAge: any;
    mobilityScore: any;
    balanceScore: any;
    strengthScore: any;
    muscleFatigueLevel: any;
    source: string;
    lastSyncAt: string;
    createdAt?: string;
}

export interface TechnogymSyncLog {
    id: string;
    businessId?: string;
    status: string;
    recordsSynced: number;
    errorMessage: any;
    createdAt?: string;
}

export interface Coupon {
    id: string;
    businessId?: string;
    customerId?: string;
    code: string;
    discountType: string;
    discountValue: number;
    expiryDate: any;
    isUsed: boolean;
    usedAt: any;
    createdAt?: string;
}

export interface Notification {
    id: string;
    businessId?: string;
    title: string;
    message: string;
    type: string;
    isRead: boolean;
    triggerSource: string;
    agentId?: any;
    createdAt?: string;
}

export interface WhatsappQueue {
    id: string;
    businessId?: string;
    recipientPhone: string;
    messageBody: string;
    status: string;
    retryCount: number;
    createdAt?: string;
    sentAt: string;
}

export interface AiTokenLog {
    id: string;
    businessId?: string;
    amount: number;
    reason: string;
    metadata: any;
    createdAt?: string;
}

export interface SystemConfig {
    key: string;
    value: string;
    description: any;
    updatedAt?: string;
}

export interface PendingAgentAction {
    id: string;
    businessId?: string;
    agentId?: string;
    actionType: string;
    payload: any;
    description: any;
    status: string;
    createdAt?: string;
    resolvedAt: any;
    resolvedBy: string;
}

export interface SaasPlan {
    id: string;
    name: string;
    code: string;
    monthlyPrice: number;
    yearlyPrice: number;
    maxUsers: number;
    maxBranches: number;
    features: any;
    isActive: boolean;
    createdAt?: string;
}

export interface SaasInvoice {
    id: string;
    businessId?: string;
    amount: number;
    currency: string;
    status: string;
    billingPeriodStart: any;
    billingPeriodEnd: any;
    invoiceUrl: any;
    paymentMethod: any;
    stripeInvoiceId?: any;
    createdAt?: string;
}

export interface WebhookEvent {
    id: string;
    gateway: string;
    externalId?: any;
    eventType: any;
    payload: any;
    processedAt: any;
    status: string;
    errorLog: any;
    createdAt?: string;
}

export interface PaymentLink {
    id: string;
    businessId?: string;
    customerId?: string;
    appointmentId?: string;
    amount: number;
    currency: string;
    status: string;
    token: string;
    description: any;
    metadata: any;
    expiresAt: string;
    createdAt?: string;
    paidAt: string;
}

export interface Business {
    id: string;
    name: string;
    ownerName: any;
    slug: string;
    plan: string;
    expiryDate: any;
    status: string;
    mrr: number;
    overrideMrr: any;
    signupPrice: any;
    maxUsers: number;
    maxBranches: number;
    managerPin: string;
    calendarStartHour: number;
    calendarEndHour: number;
    createdAt?: string;
}

export interface Branch {
    id: string;
    businessId?: string;
    name: string;
    location: any;
    address: any;
    phone: any;
    status: string;
    createdAt?: string;
}

export interface AppUser {
    id: string;
    businessId?: string;
    branchId?: string;
    staffId?: string;
    role: string;
    name: string;
    email: string;
    permissions: string[];
    allowedBranches: string[];
    createdAt?: string;
}

export interface UserBranchAccess {
    userId?: string;
    businessId?: string;
    branchId?: string;
}

export interface Staff {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    role: any;
    status: string;
    weeklyOffDay: number;
    staffType: string;
    isVisibleOnCalendar: boolean;
    sortOrder: number;
    canLoginSystem: boolean;
    canLoginMobile: boolean;
    staffGroup: string;
    lastLoginAt: any;
    createdAt?: string;
}

export interface Service {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    duration: number;
    price: number;
    category: string;
    color: string;
    consumables: any;
    isPublic: boolean;
    imageUrl: any;
    createdAt?: string;
}

export interface Product {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    category: string;
    price: number;
    stock: number;
    createdAt?: string;
}

export interface Room {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    category: string;
    color: string;
    status: string;
    createdAt?: string;
}

export interface Customer {
    id: string;
    businessId?: string;
    name: string;
    phone: any;
    email: any;
    birthdate: any;
    segment: string;
    note?: any;
    isChurnRisk: boolean;
    country: string;
    language: string;
    referenceCode: any;
    tags: string[];
    address: any;
    citizenshipNumber: any;
    gender: any;
    nationality: any;
    salesRepId?: any;
    profession: any;
    city: any;
    district: any;
    timezone: any;
    smsPermission: string;
    emailPermission: string;
    communicationSource: any;
    communicationChoice: any;
    loyaltyPoints: number;
    createdAt?: string;
    updatedAt?: string;
}

export interface CustomerMedia {
    id: string;
    businessId?: string;
    customerId?: string;
    fileUrl: string;
    fileType: any;
    note?: any;
    createdAt?: string;
}

export interface MembershipPlan {
    id: string;
    businessId?: string;
    name: string;
    price: number;
    periodDays: number;
    benefits: string[];
    allowedServices: string[];
    sessionsPerMonth: number;
    createdAt?: string;
}

export interface ReferralSource {
    id: string;
    businessId?: string;
    name: string;
    createdAt?: string;
}

export interface CustomerMembership {
    id: string;
    businessId?: string;
    customerId?: string;
    planId?: string;
    startDate: string;
    expiryDate: any;
    remainingSessions: number;
    status: string;
    createdAt?: string;
}

export interface PackageDefinition {
    id: string;
    businessId?: string;
    name: string;
    groupName: any;
    details: any;
    price: number;
    totalSessions: number;
    isActive: boolean;
    createdAt?: string;
}

export interface Package {
    id: string;
    businessId?: string;
    customerId?: string;
    definitionId?: string;
    name: string;
    serviceName: any;
    totalSessions: number;
    usedSessions: number;
    price: number;
    expiry: any;
    createdAt?: string;
}

export interface PaymentDefinition {
    id: string;
    businessId?: string;
    name: string;
    type: string;
    isActive: boolean;
    createdAt?: string;
}

export interface Payment {
    id: string;
    businessId?: string;
    branchId?: string;
    appointmentId?: any;
    customerId?: string;
    customerName: string;
    service: any;
    methods: any;
    totalAmount: number;
    paymentDefinitionId?: string;
    date: string;
    note?: any;
    tipAmount: number;
    isGift: boolean;
    originalPrice: number;
    referenceCode: any;
    giftNote: any;
    soldProducts: any;
    createdAt?: string;
}

export interface Appointment {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    customerName: string;
    service: string;
    staffId?: string;
    staffName: string;
    roomId?: string;
    date: string;
    time: string;
    duration: number;
    status: string;
    price: number;
    depositPaid: number;
    isOnline: boolean;
    packageId?: any;
    membershipId?: any;
    isPaid: boolean;
    isPackageUsage: boolean;
    paymentId?: string;
    communicationSource: any;
    selectedRegions: string[];
    bodyMapData: any;
    note?: any;
    createdAt?: string;
}

export interface CalendarBlock {
    id: string;
    businessId?: string;
    branchId?: string;
    staffId?: string;
    date: string;
    time: string;
    duration: number;
    reason: any;
    createdAt?: string;
}

export interface Debt {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    appointmentId?: string;
    amount: number;
    dueDate: any;
    description: any;
    status: string;
    customerName: any;
    createdAt?: string;
}

export interface Quote {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    customerName: string;
    serviceName: any;
    amount: number;
    status: string;
    note?: any;
    validUntil: any;
    createdAt?: string;
    updatedAt?: string;
}

export interface ConsentFormTemplate {
    id: string;
    businessId?: string;
    name: string;
    content: any;
    createdAt?: string;
    updatedAt?: string;
}

export interface BankAccount {
    id: string;
    businessId?: string;
    bankName: string;
    branchName: any;
    accountNo: any;
    iban: any;
    currency: string;
    isActive: boolean;
    createdAt?: string;
}

export interface Expense {
    id: string;
    businessId?: string;
    branchId?: string;
    desc: string;
    amount: number;
    category: string;
    date: string;
    user: any;
    createdAt?: string;
}

export interface ExpenseCategory {
    id: string;
    businessId?: string;
    name: string;
    description: any;
    createdAt?: string;
}

export interface AuditLog {
    id: string;
    businessId?: string;
    date: string;
    customerName: any;
    action: string;
    oldValue: any;
    newValue: any;
    user: any;
    createdAt?: string;
}

export interface AiInsight {
    id: string;
    businessId?: string;
    title: string;
    desc: string;
    impact: any;
    category: any;
    suggestedAction: any;
    createdAt?: string;
}

export interface CommissionRule {
    id: string;
    businessId?: string;
    staffId?: string;
    serviceName: any;
    type: string;
    value: number;
    createdAt?: string;
}

export interface BookingSettings {
    id: string;
    businessId?: string;
    branchId?: string;
    isEnabled: boolean;
    requireDeposit: boolean;
    depositPercentage: number;
    allowStaffSelect: boolean;
    bookingMessage: string;
    accentColor: string;
    maxDailySlotsPerStaff: number;
    paymentMode: 'none' | 'deposit' | 'full' | 'both';
    createdAt?: string;
    updatedAt?: string;
}

export interface SystemAnnouncement {
    id: string;
    businessId?: string;
    title: string;
    content: string;
    type: string;
    isActive: boolean;
    expiresAt: any;
    createdAt?: string;
}

export interface TenantModule {
    id: string;
    businessId?: string;
    moduleName: string;
    isEnabled: boolean;
    createdAt?: string;
}

