/**
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-types.mjs
 */

export type TableName = 'notification_logs' | 'marketing_rules' | 'dynamic_pricing_rules' | 'customer_wallets' | 'wallet_transactions' | 'consultation_body_maps' | 'inventory_usage_norms' | 'businesses' | 'branches' | 'app_users' | 'user_branch_access' | 'staff' | 'services' | 'inventory' | 'rooms' | 'customers' | 'customer_media' | 'membership_plans' | 'referral_sources' | 'customer_memberships' | 'package_definitions' | 'packages' | 'payment_definitions' | 'payments' | 'appointments' | 'calendar_blocks' | 'debts' | 'quotes' | 'consent_form_templates' | 'bank_accounts' | 'expenses' | 'expense_categories' | 'z_reports' | 'audit_logs' | 'ai_insights' | 'commission_rules' | 'booking_settings' | 'system_announcements' | 'tenant_modules';

export interface NotificationLog {
    id: string;
    businessId?: string;
    customerId?: string;
    type: string;
    content: string;
    status: string;
    sentAt: string;
    triggerSource: string;
}

export interface MarketingRule {
    id: string;
    businessId?: string;
    name: string;
    triggerType: string;
    threshold: any;
    messageTemplate: string;
    isActive: boolean;
    createdAt?: string;
    updatedAt?: string;
}

export interface DynamicPricingRule {
    id: string;
    businessId?: string;
    name: string;
    dayOfWeek: any;
    modifierPercent: number;
    isActive: boolean;
    createdAt?: string;
}

export interface CustomerWallet {
    id: string;
    businessId?: string;
    customerId?: string;
    balance: number;
    loyaltyPoints: number;
    updatedAt?: string;
}

export interface WalletTransaction {
    id: string;
    businessId?: string;
    walletId?: string;
    type: string;
    amount: number;
    points: number;
    description: any;
    createdAt?: string;
}

export interface ConsultationBodyMap {
    id: string;
    businessId?: string;
    appointmentId?: string;
    customerId?: string;
    mapData: any;
    isCritical: boolean;
    createdAt?: string;
}

export interface InventoryUsageNorm {
    id: string;
    businessId?: string;
    serviceId?: string;
    productId?: string;
    amountPerService: number;
    createdAt?: string;
}

export interface Business {
    id: string;
    name: string;
    ownerName: any;
    slug: string;
    plan: string;
    expiryDate: any;
    status: string;
    mrr: number;
    overrideMrr: any;
    signupPrice: any;
    maxUsers: number;
    maxBranches: number;
    managerPin: string;
    calendarStartHour: number;
    calendarEndHour: number;
    createdAt?: string;
}

export interface Branch {
    id: string;
    businessId?: string;
    name: string;
    location: any;
    address: any;
    phone: any;
    status: string;
    createdAt?: string;
}

export interface AppUser {
    id: string;
    businessId?: string;
    branchId?: string;
    staffId?: string;
    role: string;
    name: string;
    email: string;
    permissions: string[];
    allowedBranches: string[];
    createdAt?: string;
}

export interface UserBranchAccess {
    userId?: string;
    businessId?: string;
    branchId?: string;
}

export interface Staff {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    role: any;
    status: string;
    weeklyOffDay: number;
    staffType: string;
    isVisibleOnCalendar: boolean;
    sortOrder: number;
    canLoginSystem: boolean;
    canLoginMobile: boolean;
    staffGroup: string;
    lastLoginAt: any;
    createdAt?: string;
}

export interface Service {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    duration: number;
    price: number;
    category: string;
    color: string;
    consumables: any;
    isPublic: boolean;
    isActive: boolean;
    imageUrl: any;
    createdAt?: string;
}

export interface Product {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    category: string;
    price: number;
    stock: number;
    createdAt?: string;
}

export interface Room {
    id: string;
    businessId?: string;
    branchId?: string;
    name: string;
    category: string;
    color: string;
    status: string;
    createdAt?: string;
}

export interface Customer {
    id: string;
    businessId?: string;
    name: string;
    phone: any;
    email: any;
    birthdate: any;
    segment: string;
    note?: any;
    isChurnRisk: boolean;
    country: string;
    language: string;
    referenceCode: any;
    tags: string[];
    address: any;
    citizenshipNumber: any;
    gender: any;
    nationality: any;
    salesRepId?: any;
    profession: any;
    city: any;
    district: any;
    timezone: any;
    smsPermission: string;
    emailPermission: string;
    communicationSource: any;
    communicationChoice: any;
    loyaltyPoints: number;
    createdAt?: string;
    updatedAt?: string;
}

export interface CustomerMedia {
    id: string;
    businessId?: string;
    customerId?: string;
    fileUrl: string;
    fileType: any;
    note?: any;
    createdAt?: string;
}

export interface MembershipPlan {
    id: string;
    businessId?: string;
    name: string;
    price: number;
    periodDays: number;
    benefits: string[];
    allowedServices: string[];
    sessionsPerMonth: number;
    createdAt?: string;
}

export interface ReferralSource {
    id: string;
    businessId?: string;
    name: string;
    createdAt?: string;
}

export interface CustomerMembership {
    id: string;
    businessId?: string;
    customerId?: string;
    planId?: string;
    startDate: string;
    expiryDate: any;
    remainingSessions: number;
    status: string;
    createdAt?: string;
}

export interface PackageDefinition {
    id: string;
    businessId?: string;
    name: string;
    groupName: any;
    details: any;
    price: number;
    totalSessions: number;
    isActive: boolean;
    createdAt?: string;
}

export interface Package {
    id: string;
    businessId?: string;
    customerId?: string;
    definitionId?: string;
    name: string;
    serviceName: any;
    totalSessions: number;
    usedSessions: number;
    price: number;
    expiry: any;
    createdAt?: string;
}

export interface PaymentDefinition {
    id: string;
    businessId?: string;
    name: string;
    type: string;
    isActive: boolean;
    createdAt?: string;
}

export interface Payment {
    id: string;
    businessId?: string;
    branchId?: string;
    appointmentId?: any;
    customerId?: string;
    customerName: string;
    service: any;
    methods: any;
    totalAmount: number;
    paymentDefinitionId?: string;
    date: string;
    note?: any;
    tipAmount: number;
    isGift: boolean;
    originalPrice: number;
    referenceCode: any;
    giftNote: any;
    soldProducts: any;
    createdAt?: string;
}

export interface Appointment {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    customerName: string;
    service: string;
    staffId?: string;
    staffName: string;
    roomId?: string;
    date: string;
    time: string;
    duration: number;
    status: string;
    price: number;
    depositPaid: number;
    isOnline: boolean;
    packageId?: any;
    membershipId?: any;
    isPaid: boolean;
    isPackageUsage: boolean;
    paymentId?: string;
    communicationSource: any;
    selectedRegions: string[];
    bodyMapData: any;
    note?: any;
    createdAt?: string;
}

export interface CalendarBlock {
    id: string;
    businessId?: string;
    branchId?: string;
    staffId?: string;
    date: string;
    time: string;
    duration: number;
    reason: any;
    createdAt?: string;
}

export interface Debt {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    appointmentId?: string;
    amount: number;
    dueDate: any;
    description: any;
    status: string;
    customerName: any;
    createdAt?: string;
}

export interface Quote {
    id: string;
    businessId?: string;
    branchId?: string;
    customerId?: string;
    customerName: string;
    serviceName: any;
    amount: number;
    status: string;
    note?: any;
    validUntil: any;
    createdAt?: string;
    updatedAt?: string;
}

export interface ConsentFormTemplate {
    id: string;
    businessId?: string;
    name: string;
    content: any;
    createdAt?: string;
    updatedAt?: string;
}

export interface BankAccount {
    id: string;
    businessId?: string;
    bankName: string;
    branchName: any;
    accountNo: any;
    iban: any;
    currency: string;
    isActive: boolean;
    createdAt?: string;
}

export interface Expense {
    id: string;
    businessId?: string;
    branchId?: string;
    desc: string;
    amount: number;
    category: string;
    date: string;
    user: any;
    createdAt?: string;
}

export interface ExpenseCategory {
    id: string;
    businessId?: string;
    name: string;
    description: any;
    createdAt?: string;
}

export interface ZReport {
    id: string;
    businessId?: string;
    branchId?: string;
    reportDate: string;
    expectedNakit: number;
    actualNakit: number;
    expectedKart: number;
    actualKart: number;
    expectedHavale: number;
    actualHavale: number;
    totalDifference: number;
    closedBy: any;
    notes: any;
    createdAt?: string;
}

export interface AuditLog {
    id: string;
    businessId?: string;
    date: string;
    customerName: any;
    action: string;
    oldValue: any;
    newValue: any;
    user: any;
    createdAt?: string;
}

export interface AiInsight {
    id: string;
    businessId?: string;
    title: string;
    desc: string;
    impact: any;
    category: any;
    suggestedAction: any;
    createdAt?: string;
}

export interface CommissionRule {
    id: string;
    businessId?: string;
    staffId?: string;
    serviceName: any;
    type: string;
    value: number;
    createdAt?: string;
}

export interface BookingSettings {
    id: string;
    businessId?: string;
    branchId?: string;
    isEnabled: boolean;
    requireDeposit: boolean;
    depositPercentage: number;
    allowStaffSelect: boolean;
    bookingMessage: string;
    accentColor: string;
    createdAt?: string;
    updatedAt?: string;
}

export interface SystemAnnouncement {
    id: string;
    businessId?: string;
    title: string;
    content: string;
    type: string;
    isActive: boolean;
    expiresAt: any;
    createdAt?: string;
}

export interface TenantModule {
    id: string;
    businessId?: string;
    moduleName: string;
    isEnabled: boolean;
    createdAt?: string;
}

