import fs from 'fs';
import path from 'path';

/**
 * Aura Core - Schema Sync Tool
 * Parses SQL migrations and generates TypeScript interfaces.
 */

const MIGRATIONS_DIR = './supabase/migrations';
const OUTPUT_FILE = './lib/types/database.types.ts';

const TYPE_MAP = {
    'UUID': 'string',
    'TEXT': 'string',
    'TIMESTAMPTZ': 'string',
    'DATE': 'string',
    'INT': 'number',
    'INTEGER': 'number',
    'NUMERIC': 'number',
    'DECIMAL': 'number',
    'BOOLEAN': 'boolean',
    'JSONB': 'any',
    'TEXT[]': 'string[]'
};

function toCamelCase(str) {
    return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
}

function parseSql() {
    const files = fs.readdirSync(MIGRATIONS_DIR)
        .filter(f => f.endsWith('.sql'))
        .sort();

    const tables = {}; // name -> { columns: { name: type } }

    console.log(`Parsing ${files.length} migrations...`);

    files.forEach(file => {
        const content = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf8');
        
        // Match CREATE TABLE
        const tableMatches = content.matchAll(/CREATE TABLE (?:IF NOT EXISTS )?(?:public\.)?(\w+)\s*\(([\s\S]*?)\);/gi);
        
        for (const match of tableMatches) {
            const tableName = match[1];
            const body = match[2];
            
            if (!tables[tableName]) {
                tables[tableName] = { columns: {} };
            }

            // Simple column parser
            const lines = body.split('\n');
            lines.forEach(line => {
                const trimmed = line.trim();
                if (!trimmed || trimmed.startsWith('--') || trimmed.startsWith('PRIMARY KEY') || 
                    trimmed.startsWith('CONSTRAINT') || trimmed.startsWith('UNIQUE') || 
                    trimmed.toLowerCase().startsWith('check')) {
                    return;
                }

                const parts = trimmed.split(/\s+/);
                const colName = parts[0].toLowerCase().replace(/"/g, '');
                let colType = parts[1]?.toUpperCase() || 'TEXT';

                if (colName === 'check') return;

                // Handle NUMERIC(10,2) etc.
                if (colType.includes('(')) {
                    colType = colType.split('(')[0];
                }

                // Handle arrays
                if (trimmed.includes('TEXT[]')) colType = 'TEXT[]';
                if (trimmed.includes('UUID[]')) colType = 'TEXT[]';

                const tsType = TYPE_MAP[colType] || 'any';
                tables[tableName].columns[colName] = tsType;
            });
        }

        // Handle ALTER TABLE ADD COLUMN
        const alterMatches = content.matchAll(/ALTER TABLE (?:IF NOT EXISTS )?(?:public\.)?(\w+) ADD COLUMN (?:IF NOT EXISTS )?(\w+)\s+([\w\[\]]+)/gi);
        for (const match of alterMatches) {
            const tableName = match[1];
            const colName = match[2].toLowerCase();
            let colType = match[3].toUpperCase();
            
            if (tables[tableName]) {
                if (colType.includes('(')) colType = colType.split('(')[0];
                tables[tableName].columns[colName] = TYPE_MAP[colType] || 'any';
            }
        }
    });

    return tables;
}

function generateTs(tables) {
    let output = `/**
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by scripts/sync-types.mjs
 */

export type TableName = ${Object.keys(tables).map(t => `'${t}'`).join(' | ')};

`;

    for (const [tableName, data] of Object.entries(tables)) {
        let interfaceName = '';
        if (tableName === 'businesses') interfaceName = 'Business';
        else if (tableName === 'branches') interfaceName = 'Branch';
        else if (tableName === 'app_users') interfaceName = 'AppUser';
        else if (tableName === 'inventory') interfaceName = 'Product';
        else if (tableName === 'audit_logs') interfaceName = 'AuditLog';
        else if (tableName === 'notification_logs') interfaceName = 'NotificationLog';
        else if (tableName === 'commission_rules') interfaceName = 'CommissionRule';
        else if (tableName === 'calendar_blocks') interfaceName = 'CalendarBlock';
        else if (tableName === 'customer_media') interfaceName = 'CustomerMedia';
        else if (tableName === 'user_branch_access') interfaceName = 'UserBranchAccess';
        else if (tableName === 'booking_settings') interfaceName = 'BookingSettings';
        else if (tableName === 'ai_insights') interfaceName = 'AiInsight';
        else if (tableName === 'expense_categories') interfaceName = 'ExpenseCategory';
        else if (tableName === 'referral_sources') interfaceName = 'ReferralSource';
        else if (tableName === 'consent_form_templates') interfaceName = 'ConsentFormTemplate';
        else {
            interfaceName = tableName.charAt(0).toUpperCase() + toCamelCase(tableName.slice(1)).replace(/s$/, '');
        }
        
        output += `export interface ${interfaceName} {\n`;
        for (const [colName, type] of Object.entries(data.columns)) {
            const camelName = toCamelCase(colName);
            // Add optional flag where appropriate
            const isOptional = ['createdAt', 'updatedAt', 'syncStatus', 'deletedAt'].includes(camelName) || colName.includes('_id') || colName === 'note';
            output += `    ${camelName}${isOptional ? '?' : ''}: ${type};\n`;
        }
        output += `}\n\n`;
    }

    return output;
}

const tables = parseSql();
const tsContent = generateTs(tables);

if (!fs.existsSync('./lib/types')) {
    fs.mkdirSync('./lib/types', { recursive: true });
}

fs.writeFileSync(OUTPUT_FILE, tsContent);
console.log(`Successfully generated ${OUTPUT_FILE}`);
